#!/bin/bash
set -x
set -e
set -o pipefail

export PATH="${PATH}:/sbin"
data_block_bytes=4096
SCRIPT_BASE=$(cd -- "$(dirname -- "$0")/.."; pwd)

package_path=$(nix eval --raw nixpkgs.quasselDaemon.outPath)
package_name=$("${package_path}/bin/quasselcore" --version |
  sed -n 's/^quassel \(v[0-9]\+.[0-9]\+.[0-9]\+\)[ (].*$/quassel_\1/p')

test -e "${SCRIPT_BASE}/__cache__" && rm -rf "${SCRIPT_BASE}/__cache__"

nix copy --no-check-sigs --to "${SCRIPT_BASE}/__cache__" "${package_path}" \
  "$(nix eval --raw nixpkgs.coreutils.outPath)"
ln -s "${package_path}/bin/quasselcore" "${SCRIPT_BASE}/__cache__/nix/entrypoint"

squash_file="${SCRIPT_BASE}/${package_name}.squashfs"
squash_file_verity="${squash_file}-verity"
unlink "${squash_file}" || true
mksquashfs "${SCRIPT_BASE}/__cache__/nix" "${squash_file}" -comp xz -all-root -no-exports -no-sparse -no-xattrs
chmod u+w -R  "${SCRIPT_BASE}/__cache__"

data_length=$(stat --format="%s" "${squash_file}")
cp "${squash_file}" "${squash_file_verity}"
veritysetup format --data-block-size=${data_block_bytes} --data-blocks=$(( (${data_length} + ${data_block_bytes} - 1) / ${data_block_bytes} )) \
    --hash-offset=${data_length} "${squash_file_verity}" "${squash_file_verity}" \
    | tee "${SCRIPT_BASE}/verity-out.txt"

image_sha256=$(sha256sum "${squash_file_verity}" | awk '{print $1}')
root_hash=$(sed -n 's/^Root hash:\s\+\([0-9a-f]\{64\}\)$/\1/p' < "${SCRIPT_BASE}/verity-out.txt")

jq -aMn \
    --arg data_length "${data_length}" \
    --arg root_hash "${root_hash}" \
    --arg image_sha256 "${image_sha256}" \
    '{
        package_name: "org.yshi.x-unofficial.org.quassel-irc",
        data_length: $data_length|tonumber,
        dm_verity_root_hash: $root_hash,
        image_sha256: $image_sha256,
        image_type: "dmverity",
    }' | tee metadata.json

echo "example open execution:"
echo veritysetup open --hash-offset="${data_length}" \
    "${squash_file_verity}" "${package_name}" "${squash_file_verity}" \
    "${root_hash}"